module.exports = {
  content: [
    "./application/views/**/*.php",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#005e97",
        "primary-container": "#0077be",
        "on-primary": "#ffffff",
        "on-primary-container": "#f7f9ff",
        "on-primary-fixed-variant": "#004a79",
        "primary-fixed": "#cfe5ff",
        "primary-fixed-dim": "#9acbff",
        "on-primary-fixed": "#001d34",
        "secondary": "#9b4500",
        "secondary-container": "#fc8a40",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#672c00",
        "tertiary": "#00665a",
        "tertiary-container": "#008173",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#e4fff8",
        "surface": "#f8f9fa",
        "surface-bright": "#f8f9fa",
        "surface-dim": "#d9dadb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "surface-container": "#edeeef",
        "surface-container-high": "#e7e8e9",
        "surface-container-highest": "#e1e3e4",
        "surface-variant": "#e1e3e4",
        "on-surface": "#191c1d",
        "on-surface-variant": "#404751",
        "on-background": "#191c1d",
        "background": "#f8f9fa",
        "outline": "#707882",
        "outline-variant": "#c0c7d2",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "Kanit", "sans-serif"],
        "body": ["Be Vietnam Pro", "Kanit", "sans-serif"],
        "thai": ["Kanit", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px",
      },
    },
  },
  plugins: [],
}
